table DimEmployee
	lineageTag: 2ffa65bd-ff11-4a34-8a23-fa1746c4ed83

	column EmployeeID
		dataType: string
		lineageTag: 1be18ebf-781d-4a4a-a819-3c93421a73dd
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 7c181f54-ccab-4152-886d-c28fb27fb2f3
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: aae795fe-d3cd-4333-8f0f-d3e70a4c636a
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 2b026b5a-edd8-4f67-850e-9edff0c26769
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 0a646514-6234-4e69-a86b-2a8445981772
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column BusinessTravel
		dataType: string
		lineageTag: 4f50f612-ab19-4875-abf0-d12a9b9c4604
		summarizeBy: none
		sourceColumn: BusinessTravel

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 87d4c12d-2a6f-4101-a91a-33cee74c4c7a
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column 'DistanceFromHome (KM)'
		dataType: int64
		formatString: 0
		lineageTag: 9a042b09-a5e9-491f-bf9c-348beb7c769f
		summarizeBy: sum
		sourceColumn: DistanceFromHome (KM)

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 835a32be-c0ac-412b-b0a0-c06eb946a588
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		lineageTag: 87569ef0-dd11-43e4-8701-babdcc7e9c71
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column Education
		dataType: int64
		formatString: 0
		lineageTag: 81c19281-c1d8-42ae-984a-03ae881b263c
		summarizeBy: none
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column EducationField
		dataType: string
		lineageTag: a2573a2c-4322-42cc-91f3-d73504cd1631
		summarizeBy: none
		sourceColumn: EducationField

		annotation SummarizationSetBy = Automatic

	column JobRole
		dataType: string
		lineageTag: 606125e4-36c3-48a7-a522-2d50955c49e2
		summarizeBy: none
		sourceColumn: JobRole

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: 1cf979a1-69f1-4a16-b783-481ea371677b
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: int64
		formatString: 0
		lineageTag: 4cfbf369-1b83-41da-a040-c3b4e8736d41
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column StockOptionLevel
		dataType: int64
		formatString: 0
		lineageTag: acaaaea4-bdaa-4e39-a840-cf7cd16150a2
		summarizeBy: sum
		sourceColumn: StockOptionLevel

		annotation SummarizationSetBy = Automatic

	column OverTime
		dataType: string
		lineageTag: aefea276-b7d0-474c-9031-aa3d76a2d59f
		summarizeBy: none
		sourceColumn: OverTime

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: Mm/dd/yyyy
		lineageTag: 245eedbd-7ea0-4394-9d92-54c0bdea57e4
		summarizeBy: none
		sourceColumn: HireDate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Attrition
		dataType: string
		lineageTag: 2f144f58-901d-4eb0-b90a-079b4bb324bd
		summarizeBy: none
		sourceColumn: Attrition

		annotation SummarizationSetBy = Automatic

	column YearsAtCompany
		dataType: int64
		formatString: 0
		lineageTag: 70497431-85e9-474c-89d5-5b9a67955f24
		summarizeBy: sum
		sourceColumn: YearsAtCompany

		annotation SummarizationSetBy = Automatic

	column YearsInMostRecentRole
		dataType: int64
		formatString: 0
		lineageTag: 95293041-6205-458a-8d28-c65896e0c670
		summarizeBy: sum
		sourceColumn: YearsInMostRecentRole

		annotation SummarizationSetBy = Automatic

	column YearsSinceLastPromotion
		dataType: int64
		formatString: 0
		lineageTag: 7ae3a2c6-33e4-422b-b407-75ecb3da1f02
		summarizeBy: sum
		sourceColumn: YearsSinceLastPromotion

		annotation SummarizationSetBy = Automatic

	column YearsWithCurrManager
		dataType: int64
		formatString: 0
		lineageTag: b04f275e-4354-4974-a998-e446d3a35380
		summarizeBy: sum
		sourceColumn: YearsWithCurrManager

		annotation SummarizationSetBy = Automatic

	column AgeBins =
			SWITCH(TRUE(), DimEmployee[Age] < 20, "<\20",
			                    DimEmployee[Age] <= 29, "20-29",
			                    DimEmployee[Age] <= 39, "30-39",
			                    DimEmployee[Age] <= 49, "40-49",
			                    "50>"
			                    )
		lineageTag: d0082775-d8ca-4f88-a6f7-121251b7b359
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: 11546fb4-dff4-40b2-ac7c-1d6638c0eef9
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	partition DimEmployee = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mike.mafura\Desktop\case-study-hr-analytics-in-power-bi\Datasets\Employee.csv"),[Delimiter=",", Columns=23, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmployeeID", type text}, {"FirstName", type text}, {"LastName", type text}, {"Gender", type text}, {"Age", Int64.Type}, {"BusinessTravel", type text}, {"Department", type text}, {"DistanceFromHome (KM)", Int64.Type}, {"State", type text}, {"Ethnicity", type text}, {"Education", Int64.Type}, {"EducationField", type text}, {"JobRole", type text}, {"MaritalStatus", type text}, {"Salary", Int64.Type}, {"StockOptionLevel", Int64.Type}, {"OverTime", type text}, {"HireDate", type date}, {"Attrition", type text}, {"YearsAtCompany", Int64.Type}, {"YearsInMostRecentRole", Int64.Type}, {"YearsSinceLastPromotion", Int64.Type}, {"YearsWithCurrManager", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"HireDate", type datetime}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "FullName", each [FirstName]& "" & [LastName]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"FullName"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "FullName", each [FirstName] & " " & [LastName])
				in
				    #"Added Custom1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

