table DimEducationLevel
	lineageTag: 9b41a8b4-bef4-4647-aded-b0cd879bc079

	column EducationLevelID
		dataType: int64
		formatString: 0
		lineageTag: ba1977b2-b1b4-4d4c-90bf-71a787d1c7cb
		summarizeBy: none
		sourceColumn: EducationLevelID

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: 4ee071a2-d047-45a9-9292-8648ee05d0ca
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	partition DimEducationLevel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mike.mafura\Desktop\case-study-hr-analytics-in-power-bi\Datasets\EducationLevel.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EducationLevelID", Int64.Type}, {"EducationLevel", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

