table FactPerformanceRating
	lineageTag: 444b43f9-4816-4b0e-8fa9-f68e006b744d

	column PerformanceID
		dataType: string
		lineageTag: 77cc0d8b-b881-49be-8f32-32722226cc94
		summarizeBy: none
		sourceColumn: PerformanceID

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: string
		lineageTag: 52b2e923-f435-46a0-9331-c74f6b25ceb4
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column ReviewDate
		dataType: dateTime
		formatString: MM/DD/YYYY
		lineageTag: a654c11a-dce7-4e8a-872d-3ae05d04f78b
		summarizeBy: none
		sourceColumn: ReviewDate

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column EnvironmentSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 4e3dec0d-fee2-439b-9f70-9cc7f49b0560
		summarizeBy: none
		sourceColumn: EnvironmentSatisfaction

		annotation SummarizationSetBy = Automatic

	column JobSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: f2f27c5a-85b9-4124-9d30-92878abdf45e
		summarizeBy: sum
		sourceColumn: JobSatisfaction

		annotation SummarizationSetBy = Automatic

	column RelationshipSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 2752c93e-d525-43ca-ba38-b8535a1bb44d
		summarizeBy: sum
		sourceColumn: RelationshipSatisfaction

		annotation SummarizationSetBy = Automatic

	column TrainingOpportunitiesWithinYear
		dataType: int64
		formatString: 0
		lineageTag: 112bbac4-b90a-48dc-a423-4379a2dfe624
		summarizeBy: sum
		sourceColumn: TrainingOpportunitiesWithinYear

		annotation SummarizationSetBy = Automatic

	column TrainingOpportunitiesTaken
		dataType: int64
		formatString: 0
		lineageTag: f86b9ff5-531b-4590-aa5e-d308d15925cf
		summarizeBy: sum
		sourceColumn: TrainingOpportunitiesTaken

		annotation SummarizationSetBy = Automatic

	column WorkLifeBalance
		dataType: int64
		formatString: 0
		lineageTag: 81b899fb-d267-4c9f-b5f7-c446c6f1fe09
		summarizeBy: sum
		sourceColumn: WorkLifeBalance

		annotation SummarizationSetBy = Automatic

	column SelfRating
		dataType: int64
		formatString: 0
		lineageTag: e2121d66-e4ed-4ffa-b02e-93c245b1b010
		summarizeBy: none
		sourceColumn: SelfRating

		annotation SummarizationSetBy = Automatic

	column ManagerRating
		dataType: int64
		formatString: 0
		lineageTag: d3217354-fa34-4a4c-9ff0-825238d8c0e7
		summarizeBy: sum
		sourceColumn: ManagerRating

		annotation SummarizationSetBy = Automatic

	partition FactPerformanceRating = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mike.mafura\Desktop\case-study-hr-analytics-in-power-bi\Datasets\PerformanceRating.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PerformanceID", type text}, {"EmployeeID", type text}, {"ReviewDate", type text}, {"EnvironmentSatisfaction", Int64.Type}, {"JobSatisfaction", Int64.Type}, {"RelationshipSatisfaction", Int64.Type}, {"TrainingOpportunitiesWithinYear", Int64.Type}, {"TrainingOpportunitiesTaken", Int64.Type}, {"WorkLifeBalance", Int64.Type}, {"SelfRating", Int64.Type}, {"ManagerRating", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

